spring:
  datasource:
    url: jdbc:mysql://localhost:3306/module?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level: debug

logging:
  level:
    com.hehe.dao.mapper: debug

mybatis:
  type-aliases-package: com.hehe.*
  mapper-locations: classpath:mappers/*.xml
  #config-location: classpath:generatorConfig/mybatis-config.xml
